### ISSUE TITLE
expectd XSS vulnerability on log-service in the bot

### ISSUE THREAD

**Issue by darrkj2049** [MCwindTIM/ReiNa-Bot-Rework#1]
![vulnerability](https://user-images.githubusercontent.com/47298145/86372016-38b8ed00-bcb4-11ea-81ed-78d18931c721.png)

in these lines, the event function may suffer an XSS attack because the event triggers may return the input with no protections and checking

For example, if any user inputs an HTML or javascript in the discord chat, the bot will run those code and send it to your server.

**Comment by MCwindTIM** [comment]
[Commit 0b9bd4992eda37efbb4c8bda32fb47b7203d543b](https://github.com/MCwindTIM/ReiNa-Bot-Rework/commit/0b9bd4992eda37efbb4c8bda32fb47b7203d543b)
